### ISSUE TITLE
请教回调方法中的判断逻辑代码

### ISSUE THREAD

**Issue by ZackLee** [JeasonWong/QingtingBannerView#3]
你好 请问一下回调方法中 
`public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                bannerLine.setPageScrolled(position, positionOffset);
                if (positionOffsetPixels == 0.0) {
                    if (position == entities.size() - 1) {
                        bannerViewPager.setCurrentItem(1, false);
                    } else if (position == 0) {
                        bannerViewPager.setCurrentItem(entities.size() - 2, false);
                    } else {
                        bannerViewPager.setCurrentItem(position);
                    }
                }
            }`

`else if (position == 0) {
                        bannerViewPager.setCurrentItem(entities.size() - 2, false);
 }`

删除这个判断代码，运行效果好像没看出不同呢，请指教~

**Comment by JeasonWong** [comment]
这段代码意义是为了实现无限循环并且无闪烁现象

**Comment by ZackLee** [comment]
@JeasonWong get√ 谢谢你的答复
