### ISSUE TITLE
How to remove bottom text?

### ISSUE THREAD

**Issue by hendrawd** [JeasonWong/QingtingBannerView#9]
I dive to the code directly to find any method to hide bottom text, but can't seem to find it. Is there any way to do it?

**Comment by srtianxia** [comment]
We don't provide this api but you can clone it and modify the class [BannerLayout](https://github.com/JeasonWong/QingtingBannerView/blob/master/banner/src/main/java/me/wangyuwei/banner/BannerLayout.java) and xml [banner_layout](https://github.com/JeasonWong/QingtingBannerView/blob/master/banner/src/main/res/layout/banner_layout.xml) to adapt to your requirement.

**Comment by hendrawd** [comment]
Yes, actually i import it as project dependency, so i can edit it directly. But do you think if it can be provided? Or you guys just want this library as simple as it be? Because i think that function is useful. Another useful feature is auto slide.
